import Head from 'next/head'
import { Container } from '@nextui-org/react'
import MintZone from './components/Mintzone'
import MainText from './components/MainText'
import MyNfts from './my-nfts'

export default function Home() {

  return (
    <div style={{ justifyContent: "center", textAlign: "center" }}>
      <Head>
        <title>NFT Minting Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <MainText></MainText>
        <MintZone></MintZone>
      </Container>
    </div>
  )
}
